#
# Copyright 2025 the original author or authors.
# <p>
# Licensed under the Moderne Source Available License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# <p>
# https://docs.moderne.io/licensing/moderne-source-available-license
# <p>
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.quarkus.spring.MigrateConfigurationProperties
displayName: Migrate @ConfigurationProperties to Quarkus @ConfigMapping
description: >-
  Migrates Spring Boot @ConfigurationProperties to Quarkus @ConfigMapping.
  This recipe converts configuration property classes to the native Quarkus pattern.
tags:
  - spring
  - quarkus
  - configuration
  - migration
recipeList:
  # Add config dependency
  - org.openrewrite.java.dependencies.AddDependency:
      groupId: io.quarkus
      artifactId: quarkus-config-yaml
      version: x
      onlyIfUsing: org.springframework.boot.context.properties.ConfigurationProperties
  # Convert @ConfigurationProperties to @ConfigMapping
  - org.openrewrite.java.ChangeAnnotationAttributeName:
      annotationType: org.springframework.boot.context.properties.ConfigurationProperties
      oldAttributeName: prefix
      newAttributeName: prefix
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.context.properties.ConfigurationProperties
      newFullyQualifiedTypeName: io.smallrye.config.ConfigMapping
  # Remove @EnableConfigurationProperties since Quarkus discovers @ConfigMapping automatically
  - org.openrewrite.java.RemoveAnnotation:
      annotationPattern: org.springframework.boot.context.properties.EnableConfigurationProperties
  # Remove @ConstructorBinding (not needed in Quarkus)
  - org.openrewrite.java.RemoveAnnotation:
      annotationPattern: org.springframework.boot.context.properties.ConstructorBinding
